# Generated by Django 4.1.6 on 2023-02-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weights",
            name="organisms",
            field=models.ManyToManyField(to="infer.organism"),
        ),
    ]
