# Generated by Django 4.1.6 on 2023-02-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0004_alter_organism_ncbi_taxon"),
    ]

    operations = [
        migrations.RemoveField(model_name="weights", name="path",),
        migrations.AddField(
            model_name="weights",
            name="chkpt",
            field=models.FileField(default="", upload_to="chkpts"),
            preserve_default=False,
        ),
    ]
