# Generated by Django 4.1.6 on 2023-02-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0006_ppidatabase_remove_weights_organisms_dataset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ppidatabase",
            name="version",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
