# Generated by Django 4.1.6 on 2023-02-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0009_alter_dataset_negatives_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weights",
            name="name",
            field=models.CharField(max_length=280, unique=True),
        ),
    ]
