# Generated by Django 4.1.6 on 2023-02-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0010_alter_weights_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="weights",
            name="args",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weights",
            name="log",
            field=models.FileField(default="", upload_to="logs"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weights",
            name="spm",
            field=models.FileField(default="", upload_to="spms"),
            preserve_default=False,
        ),
    ]
