# Generated by Django 4.1.6 on 2023-02-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0011_weights_args_weights_log_weights_spm"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternateGeneName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="AlternateProteinName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="GO",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=280, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("reviewed", models.BooleanField()),
                ("entry_name", models.CharField(max_length=280)),
                ("protein_name", models.CharField(max_length=500)),
                ("gene_name", models.CharField(max_length=500)),
                ("sequence_length", models.IntegerField()),
                ("sequence", models.CharField(max_length=3000)),
                (
                    "alternate_gene_names",
                    models.ManyToManyField(to="infer.alternategenename"),
                ),
                (
                    "alternate_protein_names",
                    models.ManyToManyField(to="infer.alternateproteinname"),
                ),
                ("gene_ontologies", models.ManyToManyField(to="infer.go")),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infer.organism"
                    ),
                ),
            ],
        ),
    ]
