# Generated by Django 4.1.6 on 2023-02-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0012_alternategenename_alternateproteinname_go_protein"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProteinEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="protein",
            name="embedding",
            field=models.ManyToManyField(to="infer.proteinembedding"),
        ),
    ]
