# Generated by Django 4.1.6 on 2023-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0013_proteinembedding_protein_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proteinembedding",
            name="vector",
            field=models.CharField(max_length=3000),
        ),
    ]
