# Generated by Django 4.1.6 on 2023-02-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0014_alter_proteinembedding_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteinembedding",
            name="weights",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="infer.weights",
            ),
            preserve_default=False,
        ),
    ]
