# Generated by Django 4.1.6 on 2023-02-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0015_proteinembedding_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="weights",
            name="trunc_len",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
