# Generated by Django 4.1.6 on 2023-05-26 03:16
import datetime

from django.db import migrations


def create_weights(apps, schema_editor):
    Architecture = apps.get_model("infer", "Architecture")

    architecture = Architecture(name="INTREPPPID", version=1)
    architecture.save()

    architecture2 = Architecture(name="RAPPPID", version=1)
    architecture2.save()

    PPIDatabase = apps.get_model("infer", "PPIDatabase")
    ppi_database = PPIDatabase(
        name="STRING", version=11.5, link="https://string-db.org/"
    )
    ppi_database.save()

    Dataset = apps.get_model("infer", "Dataset")
    dataset = Dataset(
        ppi_database=ppi_database,
        c_type=3,
        train_proportion=0.8,
        val_proportion=0.1,
        test_proportion=0.1,
        neg_proportion=1.0,
        score_threshold=950,
        seed=8675309,
    )
    dataset.save()
    dataset.organisms.create(
        ncbi_taxon=9606, common_name="Human", scientific_name="Homo sapiens"
    )

    Weights = apps.get_model("infer", "Weights")

    args = {
        "lr": 0.01,
        "seed": 3927704,
        "do_rate": 0.3,
        "workers": 4,
        "log_path": "logs/e2e_rnn_triplet",
        "bi_reduce": "last",
        "chkpt_dir": "logs/e2e_rnn_triplet/23.256-13.27-distinct-stylishly/chkpt",
        "trunc_len": 1500,
        "batch_size": 80,
        "model_name": "23.256-13.27-distinct-stylishly",
        "num_epochs": 100,
        "vocab_size": 250,
        "architecture": "ClassifierBarlow",
        "embedding_size": 64,
        "optimizer_type": "ranger21_xx",
        "rnn_num_layers": 2,
        "use_projection": "false",
        "beta_classifier": 2,
        "checkpoint_path": None,
        "hyperparams_path": "logs/e2e_rnn_triplet/23.256-13.27-distinct-stylishly/hyperparams.json",
        "ppi_dataset_path": "/projects/jszym/intrepppid/data/seed_8675309/9606/intrepppid_8675309_9606.h5",
        "rnn_dropout_rate": 0.3,
        "classifier_warm_up": -1,
        "embedding_droprate": 0.3,
        "encoder_only_steps": -1,
        "sentencepiece_path": "spm.model",
        "variational_dropout": "false"
    }

    weights = Weights(
        name="distinct-stylishly",
        pub_date=datetime.date(2023, 5, 25),
        chkpt="chkpts/23.256-13.27-distinct-stylishly-epoch72-val_loss0.28.ckpt",
        spm="spms/spm_intrepppid.model",
        log="logs/distinct_stylishly.json",
        args=args,
        architecture=architecture,
        trunc_len=1500,
        dataset=dataset,
    )
    weights.save()


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0016_weights_trunc_len"),
    ]

    operations = [migrations.RunPython(create_weights)]
