# Generated by Django 4.1.5 on 2023-05-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0017_auto_20230526_0316"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProteomeTask",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=39, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("qid", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "DONE"),
                            ("P", "IN PROGRESS"),
                            ("F", "FAILED"),
                            ("Q", "QUEUED"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("sequence", models.CharField(max_length=3000)),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infer.organism"
                    ),
                ),
                (
                    "weights",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infer.weights"
                    ),
                ),
            ],
        ),
    ]
