# Generated by Django 4.1.5 on 2023-05-30 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0018_proteometask"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteometask",
            name="completion_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completion Timestamp"
            ),
        ),
        migrations.AddField(
            model_name="proteometask",
            name="submission_timestamp",
            field=models.DateTimeField(
                default=None, verbose_name="Submission Timestamp"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proteometask",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "DONE"),
                    ("P", "IN PROGRESS"),
                    ("F", "FAILED"),
                    ("Q", "QUEUED"),
                ],
                default="",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProteomeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("probability", models.FloatField()),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infer.protein"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infer.proteometask",
                    ),
                ),
            ],
        ),
    ]
