# Generated by Django 4.1.6 on 2023-07-17 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infer", "0019_proteometask_completion_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProteomeResultStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statistic", models.CharField(max_length=3000)),
                ("value", models.CharField(max_length=3000)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infer.proteometask",
                    ),
                ),
            ],
        ),
    ]
